version: '2'
services:
  base: &base
    image: ruby:2.4.0
    working_dir: /home/app/proly
    volumes:
      - .:/home/app/proly
      - proly_gems_2_4_0:/usr/local/bundle

  #################### CONTAINERS ####################

  proly:
    <<: *base
    container_name: proly
    command: bash -c 'gem install bundler; bundle install'

volumes:
  proly_gems_2_4_0:
